-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 21:09:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Book
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Book` DEFAULT CHARACTER SET utf8 ;
USE `Book` ;

-- -----------------------------------------------------
-- Table `Book`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book`.`Category` ;

CREATE TABLE IF NOT EXISTS `Book`.`Category` (
  `CategoryId` INT NOT NULL,
  `CategoryName` VARCHAR(100) NOT NULL,
  `Duration` VARCHAR(45) NOT NULL,
  `CategoryDescription` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`CategoryId`),
  UNIQUE INDEX `CategoryName_UNIQUE` (`CategoryName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Book`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book`.`booking` ;

CREATE TABLE IF NOT EXISTS `Book`.`booking` (
  `bookingId` INT NOT NULL,
  `bookingName` VARCHAR(100) NOT NULL,
  `StartTime` DATETIME NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Note` VARCHAR(255) NULL,
  `Category_CategoryId` INT NOT NULL,
  PRIMARY KEY (`bookingId`),
  INDEX `fk_booking_Category_idx` (`Category_CategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_booking_Category`
    FOREIGN KEY (`Category_CategoryId`)
    REFERENCES `Book`.`Category` (`CategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

